import type { Metadata } from "next";
import { Alef } from "next/font/google";
import "../app/assets/scss/main.scss";
import NavBar from "./cmps/NavBar";

const alef = Alef({ subsets:['hebrew'],  weight: ['400'] });

export const metadata: Metadata = {
  title: "ידיעת הארץ -זיקים בארי",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={alef.className} lang="en">
      
      <body className={`main-layout`} >
     <NavBar/>
        {children}
        
        </body>
    </html>
  );
}
